version: 1.0.{build}
install:
  - git submodule update --init --recursive
before_build:
  - nuget restore
build:
  project: gta5-extended-video-export/gta5-lossless-render.vcxproj
  verbosity: minimal
test: off
